<a href="https://colab.research.google.com/github/Phruetti/DPDM65/blob/main/final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive # เชื่อม google drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

In [24]:
data_train = pd.read_csv('/content/drive/MyDrive/DPDM65/train.csv')
data_train

,Unnamed: 0,id,project_name,company,province,district,sub_district,property_type,home improvement,renovate,...,number_of_bathroom,number_of_parking,usable_area,central_cost,direction,furniture,building_number,number_of_building,floor_number,parking_percentage
0,0,676.0,กันยารัตน์ ฟลอร่า วิลล์,บริษัท กันยารัตน์ พร็อพเพอร์ตี้ จำกัด,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,no,no,...,NaN,0.0,0.0,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN
1,1,19711.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ศิลา,ที่ดิน,NaN,NaN,...,NaN,NaN,NaN,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN
2,2,30146P,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,NaN,NaN,...,2.0,1.0,208.0,NaN,NaN,"ฟรี! แอร์ 2 เครื่อง, เครื่องทำน้ำอุ่น 2 เครื่อ...",NaN,NaN,NaN,NaN
3,3,1899.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,แดงใหญ่,บ้านเดี่ยว,no,no,...,3.0,3.0,145.0,0.0,ไม่ระบุ,ไม่มี,NaN,NaN,NaN,NaN
4,4,23503.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,บ้านค้อ,บ้านเดี่ยว,no,no,...,2.0,3.0,114.0,0.0,ตะวันออกเฉียงใต้,ไม่ระบุ,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2720,2720,5130.0,เดอะ มอร์ ศรีจันทร์ ขอนแก่น,บริษัท วี ไอ พี แกรนด์ จำกัด,ขอนแก่น,เมืองขอนแก่น,พระลับ,บ้านเดี่ยว,no,no,...,6.0,5.0,0.0,1350.0,เหนือ,ตกแต่งครบ,NaN,NaN,NaN,NaN
2721,2721,30284P,NaN,NaN,ขอนแก่น,บ้านแฮด,บ้านแฮด,ที่ดิน,NaN,NaN,...,NaN,NaN,4625.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2722,2722,6326.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,บ้านทุ่ม,บ้านเดี่ยว,no,no,...,0.0,0.0,0.0,0.0,ไม่ระบุ,ไม่ระบุ,NaN,NaN,0.0,NaN
2723,2723,6045.0,กันยารัตน์ การ์เด้นวิว รีสอร์ท,บริษัท กันยารัตน์ พร็อพเพอร์ตี้ จำกัด,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,no,no,...,0.0,0.0,0.0,0.0,ไม่ระบุ,ไม่ระบุ,NaN,NaN,0.0,NaN
2724,2724,18085.0,NaN,NaN,ขอนแก่น,พล,เมืองพล,บ้านเดี่ยว,no,no,...,0.0,0.0,0.0,0.0,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN

In [30]:
data_test = pd.read_csv('/content/drive/MyDrive/DPDM65/additional_data_newhouse.csv')
data_test

,Unnamed: 0,id,parent_id,project_name,province,district,sub_district,zip_code,zone_id,zone,...,cable_range,cable_min,cable_max,cable_free,cable_none,cable_ask,position_previous,position_current,sold_out_at,is_pro_in_house
0,0,314.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
1,1,315.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
2,2,316.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
3,3,317.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
4,4,318.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,988,5fa0e476a3326800191e29ea,5fa10335d0235b0019c19548,เดอะ เล็ก วิวล์ @พล,ขอนแก่น,พล,โจดหนองแก,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
989,989,5e9d6fa69f161600121b61b2,5e9d70b19f161600121b61bc,เดอะ เล็ก วิวล์ @แวงน้อย,ขอนแก่น,แวงน้อย,แวงน้อย,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990,990,5e9d6fa69f161600121b61b2,5e9d70379f161600121b61b7,เดอะ เล็ก วิวล์ @แวงน้อย,ขอนแก่น,แวงน้อย,แวงน้อย,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
991,991,5e9d6fa69f161600121b61b2,5e9d71739f161600121b61c2,เดอะ เล็ก วิวล์ @แวงน้อย,ขอนแก่น,แวงน้อย,แวงน้อย,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992,992,5ea938d968253d0012adc1e2,5ea9391e68253d0012adc1e5,วิชญาพัส วิลล์ @บ้านทุ่ม,ขอนแก่น,เมืองขอนแก่น,บ้านทุ่ม,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### cleaning data

In [12]:
import numpy as np

In [48]:

data_train.shape

(2725, 41)

In [49]:
data_test.shape

(993, 139)

In [78]:
data_train.dtypes

Unnamed: 0              int64
id                     object
project_name           object
company                object
province               object
district               object
sub_district           object
property_type          object
home improvement       object
renovate               object
public utility         object
land type              object
land wide(m)          float64
land long(m)           object
topsoil                object
corner                 object
zip_code              float64
zone                   object
alley                  object
street                 object
latitude               object
longitude              object
number_of_rai         float64
number_of_ngan         object
number_of_va          float64
construct_year        float64
model                 float64
sell_price            float64
number_of_unit         object
number_of_story        object
number_of_bedroom      object
number_of_bathroom     object
number_of_parking      object
usable_area            object
central_cost           object
direction              object
furniture              object
building_number        object
number_of_building     object
floor_number           object
parking_percentage     object
SELL                     bool
dtype: object

In [32]:
data_test.dtypes

Unnamed: 0             int64
id                    object
parent_id             object
project_name          object
province              object
                      ...
cable_ask            float64
position_previous    float64
position_current     float64
sold_out_at          float64
is_pro_in_house      float64
Length: 139, dtype: object

In [79]:
data_train['sell_price'] = pd.to_numeric(data_train['sell_price'],errors='coerce')
data_train.describe()

,Unnamed: 0,land wide(m),zip_code,number_of_rai,number_of_va,construct_year,model,sell_price
count,2725.000000,315.000000,1.741000e+03,2725.000000,2725.000000,0.0,0.0,2.715000e+03
mean,1362.000000,55.456159,4.635122e+06,3.561101,44.054606,NaN,NaN,2.837311e+07
std,786.784066,75.585414,1.355348e+08,15.905963,58.956727,NaN,NaN,7.713639e+08
min,0.000000,4.000000,4.000000e+04,0.000000,0.000000,NaN,NaN,0.000000e+00
25%,681.000000,12.000000,4.000000e+04,0.000000,5.000000,NaN,NaN,1.450000e+06
50%,1362.000000,27.500000,4.000000e+04,0.000000,35.000000,NaN,NaN,2.590000e+06
75%,2043.000000,65.000000,4.013000e+04,0.000000,66.000000,NaN,NaN,4.900000e+06
max,2724.000000,420.000000,4.000040e+09,458.000000,1656.000000,NaN,NaN,4.000000e+10

In [67]:
mean_tr=data_train['sell_price'].mean()
mean_tr

28373107.167219155

In [62]:
from matplotlib import pyplot as plt

In [97]:
data_train['SELL']=data_train['sell_price']>=28373107 #มากกว่าเท่ากับ 10
data_train

,Unnamed: 0,id,project_name,company,province,district,sub_district,property_type,home improvement,renovate,...,number_of_parking,usable_area,central_cost,direction,furniture,building_number,number_of_building,floor_number,parking_percentage,SELL
0,0,676.0,กันยารัตน์ ฟลอร่า วิลล์,บริษัท กันยารัตน์ พร็อพเพอร์ตี้ จำกัด,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,no,no,...,0.0,0.0,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN,False
1,1,19711.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ศิลา,ที่ดิน,NaN,NaN,...,NaN,NaN,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN,False
2,2,30146P,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,NaN,NaN,...,1.0,208.0,NaN,NaN,"ฟรี! แอร์ 2 เครื่อง, เครื่องทำน้ำอุ่น 2 เครื่อ...",NaN,NaN,NaN,NaN,False
3,3,1899.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,แดงใหญ่,บ้านเดี่ยว,no,no,...,3.0,145.0,0.0,ไม่ระบุ,ไม่มี,NaN,NaN,NaN,NaN,False
4,4,23503.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,บ้านค้อ,บ้านเดี่ยว,no,no,...,3.0,114.0,0.0,ตะวันออกเฉียงใต้,ไม่ระบุ,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2720,2720,5130.0,เดอะ มอร์ ศรีจันทร์ ขอนแก่น,บริษัท วี ไอ พี แกรนด์ จำกัด,ขอนแก่น,เมืองขอนแก่น,พระลับ,บ้านเดี่ยว,no,no,...,5.0,0.0,1350.0,เหนือ,ตกแต่งครบ,NaN,NaN,NaN,NaN,False
2721,2721,30284P,NaN,NaN,ขอนแก่น,บ้านแฮด,บ้านแฮด,ที่ดิน,NaN,NaN,...,NaN,4625.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2722,2722,6326.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,บ้านทุ่ม,บ้านเดี่ยว,no,no,...,0.0,0.0,0.0,ไม่ระบุ,ไม่ระบุ,NaN,NaN,0.0,NaN,False
2723,2723,6045.0,กันยารัตน์ การ์เด้นวิว รีสอร์ท,บริษัท กันยารัตน์ พร็อพเพอร์ตี้ จำกัด,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,no,no,...,0.0,0.0,0.0,ไม่ระบุ,ไม่ระบุ,NaN,NaN,0.0,NaN,False
2724,2724,18085.0,NaN,NaN,ขอนแก่น,พล,เมืองพล,บ้านเดี่ยว,no,no,...,0.0,0.0,0.0,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN,False

In [101]:
df_pr=pd.get_dummies(data_train,columns=['Sex']) 
df_pr

KeyError: ignored

###เริ่มทำ data Regression

In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [60]:
TRAIN = data_train.iloc[:1900,:]
TEST = data_train.iloc[1900:,:]
print(f'train={TRAIN.shape[0]},test={TEST.shape[0]}')

train=1900,test=825

In [116]:
x=TRAIN.drop(columns=['sell_price'])
x

,Unnamed: 0,id,project_name,company,province,district,sub_district,property_type,home improvement,renovate,...,number_of_bathroom,number_of_parking,usable_area,central_cost,direction,furniture,building_number,number_of_building,floor_number,parking_percentage
0,0,676.0,กันยารัตน์ ฟลอร่า วิลล์,บริษัท กันยารัตน์ พร็อพเพอร์ตี้ จำกัด,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,no,no,...,NaN,0.0,0.0,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN
1,1,19711.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ศิลา,ที่ดิน,NaN,NaN,...,NaN,NaN,NaN,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN
2,2,30146P,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,NaN,NaN,...,2.0,1.0,208.0,NaN,NaN,"ฟรี! แอร์ 2 เครื่อง, เครื่องทำน้ำอุ่น 2 เครื่อ...",NaN,NaN,NaN,NaN
3,3,1899.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,แดงใหญ่,บ้านเดี่ยว,no,no,...,3.0,3.0,145.0,0.0,ไม่ระบุ,ไม่มี,NaN,NaN,NaN,NaN
4,4,23503.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,บ้านค้อ,บ้านเดี่ยว,no,no,...,2.0,3.0,114.0,0.0,ตะวันออกเฉียงใต้,ไม่ระบุ,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1895,1895,20146.0,สุรินดา กลางเมือง,NaN,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,บ้านเดี่ยว,yes,yes,...,3.0,2.0,160.0,804.0,ตะวันออกเฉียงเหนือ,ตกแต่งครบ,NaN,NaN,NaN,NaN
1896,1896,20391P,NaN,NaN,ขอนแก่น,ชุมแพ,หนองไผ่,ที่ดิน,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1897,1897,10385P,เดอะ เบสไฮท์ มิตรภาพ ขอนแก่น,บริษัท แสนสิริ จำกัด (มหาชน),ขอนแก่น,เมืองขอนแก่น,ในเมือง,คอนโด,no,no,...,1.0,0.0,29.0,NaN,NaN,ไม่ระบุ,NaN,NaN,8.0,NaN
1898,1898,8924.0,NaN,NaN,ขอนแก่น,ภูเวียง,บ้านเรือ,ที่ดิน,NaN,NaN,...,NaN,NaN,NaN,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN
1899,1899,17505.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ในเมือง,ทาวน์โฮม,no,no,...,0.0,0.0,0.0,0.0,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN

In [118]:
y=TRAIN.iloc[:,10]
y

0           NaN
1           yes
2           NaN
3           NaN
4           NaN
         ...
1895        NaN
1896    ไม่ระบุ
1897        NaN
1898    ไม่ระบุ
1899        NaN
Name: public utility, Length: 1900, dtype: object

In [120]:
plt.figure(figsize=(12,9))
plt.scatter(TRAIN["x"], TEST["y"])
plt.xlabel("x")
plt.ylabel("y")

KeyError: ignored

In [106]:
x_train=TRAIN.drop(columns=['sell_price'])
x_train

,Unnamed: 0,id,project_name,company,province,district,sub_district,property_type,home improvement,renovate,...,number_of_bathroom,number_of_parking,usable_area,central_cost,direction,furniture,building_number,number_of_building,floor_number,parking_percentage
0,0,676.0,กันยารัตน์ ฟลอร่า วิลล์,บริษัท กันยารัตน์ พร็อพเพอร์ตี้ จำกัด,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,no,no,...,NaN,0.0,0.0,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN
1,1,19711.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ศิลา,ที่ดิน,NaN,NaN,...,NaN,NaN,NaN,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN
2,2,30146P,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ในเมือง,บ้านเดี่ยว,NaN,NaN,...,2.0,1.0,208.0,NaN,NaN,"ฟรี! แอร์ 2 เครื่อง, เครื่องทำน้ำอุ่น 2 เครื่อ...",NaN,NaN,NaN,NaN
3,3,1899.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,แดงใหญ่,บ้านเดี่ยว,no,no,...,3.0,3.0,145.0,0.0,ไม่ระบุ,ไม่มี,NaN,NaN,NaN,NaN
4,4,23503.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,บ้านค้อ,บ้านเดี่ยว,no,no,...,2.0,3.0,114.0,0.0,ตะวันออกเฉียงใต้,ไม่ระบุ,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1895,1895,20146.0,สุรินดา กลางเมือง,NaN,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,บ้านเดี่ยว,yes,yes,...,3.0,2.0,160.0,804.0,ตะวันออกเฉียงเหนือ,ตกแต่งครบ,NaN,NaN,NaN,NaN
1896,1896,20391P,NaN,NaN,ขอนแก่น,ชุมแพ,หนองไผ่,ที่ดิน,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1897,1897,10385P,เดอะ เบสไฮท์ มิตรภาพ ขอนแก่น,บริษัท แสนสิริ จำกัด (มหาชน),ขอนแก่น,เมืองขอนแก่น,ในเมือง,คอนโด,no,no,...,1.0,0.0,29.0,NaN,NaN,ไม่ระบุ,NaN,NaN,8.0,NaN
1898,1898,8924.0,NaN,NaN,ขอนแก่น,ภูเวียง,บ้านเรือ,ที่ดิน,NaN,NaN,...,NaN,NaN,NaN,NaN,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN
1899,1899,17505.0,NaN,NaN,ขอนแก่น,เมืองขอนแก่น,ในเมือง,ทาวน์โฮม,no,no,...,0.0,0.0,0.0,0.0,ไม่ระบุ,ไม่ระบุ,NaN,NaN,NaN,NaN